const whoReadsPortfolio = {
  id: 'who-reads-a-portfolio',
  number: '05',
  datePublished: '2026-07-30',
  tags: ['Professional Identity', 'Portfolio', 'Career Development'],
  translations: {
    es: {
      slug: 'quien-lee-un-portfolio',
      kicker: 'Identidad profesional',
      cardCopete:
        'Antes de convencer a otros, un portfolio obliga a ordenar la propia trayectoria y decidir qué clase de profesional se es hoy.',
      title: '¿Quién lee un portfolio?',
      copete:
        'Un portfolio parece estar construido para reclutadores, clientes o responsables técnicos. Sin embargo, su primer lector es quien lo crea. Antes de convencer a otros, obliga a ordenar la propia trayectoria, elegir qué mostrar y responder una pregunta difícil: ¿qué clase de profesional soy hoy?',
      bajada:
        'Es legítimo preguntarse cuántas personas visitarán un portfolio y cuánto tiempo dedicarán a recorrerlo. Pero reducir su valor a la atención externa es ignorar una parte esencial: construirlo también permite revisar la propia historia, reconocer capacidades, detectar vacíos y decidir hacia dónde avanzar.',
      sections: [
        {
          heading: 'La pregunta inevitable',
          paragraphs: [
            'Después de invertir tiempo en diseñar, escribir y publicar un portfolio aparece una pregunta difícil de evitar:',
            '¿Quién va a leer todo esto?',
            'La respuesta más honesta probablemente no sea tranquilizadora. Muchos reclutadores abrirán el enlace durante pocos segundos. Algunos observarán solamente el encabezado, la experiencia reciente y las tecnologías principales. Un responsable técnico quizá visite GitHub. Otros no llegarán a abrirlo.',
            'Entonces surge una duda razonable: ¿vale la pena construir un portfolio si no sabemos quién lo leerá?',
            'Creo que sí, pero no únicamente por las visitas que pueda recibir.',
            'Un portfolio no es solo una pieza de comunicación dirigida hacia afuera. También es una herramienta para observarse profesionalmente desde cierta distancia.',
          ],
        },
        {
          heading: 'Una narrativa, no solamente una lista',
          paragraphs: [
            'Un currículum resume. LinkedIn clasifica. GitHub expone repositorios. Un portfolio permite construir una narrativa.',
            'No se limita a enumerar empleos, tecnologías y estudios. Puede mostrar cómo se relacionan:',
            'qué experiencia tengo; qué problemas sé resolver; cómo trabajo; qué estoy construyendo; qué pienso sobre la industria; hacia dónde quiero avanzar.',
            'Una trayectoria puede incluir backend, arquitectura, integración, coordinación técnica y desarrollo full-stack. Presentados como una lista, esos elementos parecen fragmentos. Dentro de un portfolio pueden formar una identidad profesional comprensible.',
            'El sitio funciona como una interfaz entre una trayectoria compleja y alguien que todavía no la conoce.',
          ],
        },
        {
          heading: 'El primer lector es uno mismo',
          paragraphs: [
            'Mientras construía mi portfolio, advertí que muchas decisiones aparentemente visuales eran en realidad decisiones sobre mi identidad profesional.',
            '¿Qué título debía utilizar? ¿Senior Software Engineer o Senior Software Developer? ¿Qué lugar debía ocupar Java? ¿Debía presentarme principalmente como desarrollador backend o como full-stack? ¿Cómo incorporar el uso de inteligencia artificial sin hacer que pareciera más importante que dieciocho años de experiencia? ¿Qué trabajos y proyectos representaban mejor mi recorrido actual?',
            'Estas preguntas no se responden modificando CSS. Exigen revisar la propia historia y decidir qué versión de ella se quiere sostener públicamente.',
            'Al intentar explicarle a otro quién soy profesionalmente, tuve que explicármelo primero a mí mismo.',
          ],
        },
        {
          heading: 'Elegir también significa renunciar',
          paragraphs: [
            'Una trayectoria extensa contiene demasiadas experiencias, tecnologías y responsabilidades como para mostrarlo todo con el mismo peso.',
            'Intentar incluir cada elemento no produce una imagen más completa. Generalmente produce ruido.',
            'Presentarme como desarrollador Java senior significa que otras tecnologías quedan en un plano complementario. Destacar aplicaciones empresariales e integración significa no centrar el discurso en trabajos frontend aislados.',
            'Hablar de desarrollo aumentado por IA exige aclarar que la dirección, la revisión y la responsabilidad siguen siendo humanas.',
            'Mostrar proyectos de portfolio requiere distinguirlos de proyectos comerciales o realizados para clientes.',
            'Estas elecciones obligan a abandonar la idea de que una identidad profesional debe contener todas las versiones posibles de uno mismo.',
            'Un portfolio no responde exhaustivamente quién fui. Intenta mostrar quién soy ahora y qué puede esperarse de mí.',
          ],
        },
        {
          heading: 'La coherencia no aparece sola',
          paragraphs: [
            'Es frecuente que nuestros canales profesionales cuenten historias diferentes.',
            'El currículum puede presentarnos de una manera. LinkedIn, de otra. GitHub puede estar dominado por repositorios antiguos que ya no representan nuestro nivel. Una biografía escrita años atrás puede seguir describiendo objetivos que ya no tenemos.',
            'Mientras esos elementos permanecen separados, las contradicciones pueden pasar inadvertidas. El portfolio las reúne.',
            'Si alguien se presenta como desarrollador backend senior, pero sus repositorios visibles son ejercicios básicos, existe una incoherencia.',
            'Si afirma usar inteligencia artificial profesionalmente, pero no puede explicar cómo la utiliza ni qué responsabilidad conserva, existe otra.',
            'El proceso de construir un portfolio obliga a revisar esas fracturas y alinear la forma en que nos mostramos con aquello que realmente podemos sostener.',
          ],
        },
        {
          heading: 'De las afirmaciones a las evidencias',
          paragraphs: [
            'Un currículum está compuesto principalmente por afirmaciones:',
            'Experiencia en Java. Conocimientos de integración. Capacidad para desarrollar aplicaciones full-stack. Uso profesional de inteligencia artificial.',
            'Un portfolio permite acompañar esas afirmaciones con evidencias.',
            'Un proyecto puede mostrar el problema, la arquitectura, las tecnologías, las pruebas, el tiempo de desarrollo, la metodología, sus límites y el repositorio.',
            'Un artículo puede mostrar cómo se piensa una cuestión técnica o profesional.',
            'El propio sitio puede convertirse en evidencia de diseño, internacionalización, accesibilidad, SEO, despliegue y mantenimiento.',
            'Un buen portfolio no reemplaza la experiencia, pero reduce la distancia entre decir y demostrar.',
          ],
        },
        {
          heading: 'También muestra lo que falta',
          paragraphs: [
            'Al crear una sección de proyectos no solo se decide qué mostrar. También se descubre qué capacidades todavía no tienen una evidencia pública suficiente.',
            'Tal vez exista experiencia real con integración, pero ningún proyecto visible que la demuestre.',
            'Tal vez se conozca Spring Boot, pero falte una aplicación publicada y documentada.',
            'Tal vez se haya trabajado durante años en sistemas empresariales, pero nunca se haya explicado qué decisiones los hacen confiables.',
            'Ese vacío puede convertirse en una hoja de ruta.',
            'Los próximos proyectos dejan de elegirse solamente porque parecen interesantes. Empiezan a elegirse porque completan una imagen profesional:',
            'uno puede demostrar backend y persistencia; otro, integración y mensajería; otro, seguridad y arquitectura; otro, uso responsable de IA.',
            'Así, el portfolio no es solo un registro del trabajo pasado. También puede organizar el trabajo futuro.',
          ],
        },
        {
          heading: 'Una memoria profesional',
          paragraphs: [
            'Con el tiempo es fácil olvidar cuánto se hizo.',
            'Los proyectos terminan, las empresas cambian, las tecnologías se reemplazan y los detalles desaparecen detrás de nuevas responsabilidades.',
            'Un portfolio conserva una memoria seleccionada:',
            'qué construí; qué problemas resolví; qué tecnologías utilicé; qué aprendí; cómo pensaba en ese momento; qué cambió después.',
            'No es un archivo neutral. Toda presentación implica una selección. Pero esa selección permite reconocer una continuidad donde antes parecía haber episodios aislados.',
            'También permite ver la evolución. Un proyecto antiguo puede mostrar una etapa. Uno nuevo puede evidenciar un cambio de nivel, metodología o ambición.',
          ],
        },
        {
          heading: 'No es una obra terminada',
          paragraphs: [
            'Existe el riesgo de tratar el portfolio como una obra definitiva.',
            'Buscar que todo esté perfecto antes de publicarlo puede convertirlo en una tarea interminable. Siempre faltará un proyecto, una traducción, una corrección visual o una mejor descripción.',
            'Pero una identidad profesional tampoco está terminada.',
            'Por eso, un portfolio puede entenderse mejor como un sistema vivo. Se publica cuando representa dignamente el presente y luego evoluciona:',
            'se agregan proyectos; se corrigen imprecisiones; se actualiza la experiencia; se publican artículos; se eliminan elementos que dejaron de ser relevantes; se ajusta el discurso.',
            'Esta evolución no es una falla. Es parte de su función.',
            'El portfolio no debería fingir que la trayectoria está completa. Debería mostrar que tiene dirección.',
          ],
        },
        {
          heading: 'Entonces, ¿quién lo lee?',
          paragraphs: [
            'Puede leerlo un reclutador que necesita comprender rápidamente un perfil.',
            'Puede leerlo un responsable técnico que busca señales de criterio y experiencia.',
            'Puede leerlo un colega, un posible cliente o alguien que llegó desde un artículo.',
            'También puede no leerlo casi nadie durante una semana.',
            'Pero existe otro lector que siempre está presente: quien lo construye.',
            'Ese lector utiliza el portfolio para revisar su pasado, ordenar su presente y proyectar su futuro.',
            'La utilidad externa depende de factores que no controlamos completamente: tráfico, oportunidades, procesos de selección y atención ajena.',
            'La utilidad interna comienza desde el momento en que intentamos responder con honestidad:',
            '¿Qué quiero mostrar, qué puedo demostrar y qué me falta construir?',
          ],
        },
        {
          heading: 'Construir para ser visto y para verse',
          paragraphs: [
            'Un portfolio debe estar pensado para otros. Tiene que ser claro, accesible y fácil de recorrer. No puede convertirse en un ejercicio puramente autobiográfico.',
            'Pero tampoco debería medirse solamente por la cantidad de visitas.',
            'Su construcción puede producir algo anterior a cualquier oportunidad laboral: una comprensión más precisa de la propia posición profesional.',
            'Obliga a encontrar un hilo entre experiencias dispersas.',
            'Convierte capacidades en evidencias.',
            'Expone contradicciones.',
            'Revela vacíos.',
            'Organiza proyectos futuros.',
            'Quizá muchas personas no lean un portfolio completo.',
            'Aun así, puede valer la pena construirlo.',
            'Porque no solo creamos un lugar para que otros nos conozcan.',
            'También construimos un lugar desde el cual reconocernos.',
          ],
        },
      ],
    },
    en: {
      slug: 'who-reads-a-portfolio',
      kicker: 'Professional identity',
      cardCopete:
        'Before persuading others, a portfolio forces us to organise our own path and decide what kind of professional we are today.',
      title: 'Who Reads a Portfolio?',
      copete:
        'A portfolio appears to be built for recruiters, clients, or technical decision-makers. Yet its first reader is the person who creates it. Before persuading others, it forces us to organise our own path, choose what to show, and answer a difficult question: what kind of professional am I today?',
      bajada:
        'It is legitimate to wonder how many people will visit a portfolio and how much time they will spend exploring it. But reducing its value to external attention ignores an essential part of the process: building one also allows us to review our own history, recognise capabilities, identify gaps, and decide where to go next.',
      sections: [
        {
          heading: 'The inevitable question',
          paragraphs: [
            'After investing time in designing, writing, and publishing a portfolio, a difficult question inevitably appears:',
            'Who is going to read all this?',
            'The most honest answer is probably not reassuring. Many recruiters will open the link for only a few seconds. Some will look only at the heading, recent experience, and primary technologies. A technical decision-maker may visit GitHub. Others will never open it.',
            'That raises a reasonable doubt: is building a portfolio worthwhile when we do not know who will read it?',
            'I believe it is, but not only because of the visits it may receive.',
            'A portfolio is not merely a piece of communication aimed outward. It is also a tool for observing oneself professionally from a certain distance.',
          ],
        },
        {
          heading: 'A narrative, not merely a list',
          paragraphs: [
            'A CV summarises. LinkedIn classifies. GitHub exposes repositories. A portfolio makes it possible to build a narrative.',
            'It does not merely list jobs, technologies, and studies. It can show how they relate:',
            'what experience I have; which problems I can solve; how I work; what I am building; what I think about the industry; where I want to go next.',
            'A career may include backend development, architecture, integration, technical coordination, and full-stack development. Presented as a list, these elements look like fragments. Within a portfolio, they can form a comprehensible professional identity.',
            'The site acts as an interface between a complex career and someone who does not yet know it.',
          ],
        },
        {
          heading: 'The first reader is oneself',
          paragraphs: [
            'While building my portfolio, I realised that many apparently visual decisions were actually decisions about my professional identity.',
            'Which title should I use? Senior Software Engineer or Senior Software Developer? What place should Java occupy? Should I present myself primarily as a backend or full-stack developer? How could I incorporate artificial intelligence without making it appear more important than eighteen years of experience? Which jobs and projects best represented my current path?',
            'These questions cannot be answered by modifying CSS. They require us to review our own history and decide which version of it we are prepared to uphold publicly.',
            'In trying to explain to someone else who I am professionally, I first had to explain it to myself.',
          ],
        },
        {
          heading: 'Choosing also means giving something up',
          paragraphs: [
            'A long career contains too many experiences, technologies, and responsibilities to give them all equal weight.',
            'Trying to include every element does not produce a more complete picture. It generally produces noise.',
            'Presenting myself as a senior Java developer means that other technologies take a complementary role. Highlighting enterprise applications and integration means not centring the narrative on isolated frontend work.',
            'Discussing AI-augmented development requires clarifying that direction, review, and responsibility remain human.',
            'Showing portfolio projects requires distinguishing them from commercial or client work.',
            'These choices force us to abandon the idea that a professional identity must contain every possible version of ourselves.',
            'A portfolio does not answer exhaustively who I was. It attempts to show who I am now and what others can expect from me.',
          ],
        },
        {
          heading: 'Coherence does not appear by itself',
          paragraphs: [
            'Our professional channels often tell different stories.',
            'A CV may present us one way and LinkedIn another. GitHub may be dominated by old repositories that no longer represent our level. A biography written years ago may still describe goals we no longer have.',
            'While those elements remain separate, contradictions can go unnoticed. A portfolio brings them together.',
            'If someone presents themselves as a senior backend developer while their visible repositories contain only basic exercises, there is an inconsistency.',
            'If they claim to use artificial intelligence professionally but cannot explain how they use it or which responsibility they retain, there is another.',
            'Building a portfolio forces us to examine these fractures and align how we present ourselves with what we can genuinely sustain.',
          ],
        },
        {
          heading: 'From claims to evidence',
          paragraphs: [
            'A CV consists mainly of claims:',
            'Experience with Java. Knowledge of integration. Ability to develop full-stack applications. Professional use of artificial intelligence.',
            'A portfolio can accompany those claims with evidence.',
            'A project can show the problem, architecture, technologies, tests, development time, methodology, limitations, and repository.',
            'An article can show how someone thinks about a technical or professional issue.',
            'The site itself can become evidence of design, internationalisation, accessibility, SEO, deployment, and maintenance.',
            'A good portfolio does not replace experience, but it narrows the distance between saying and demonstrating.',
          ],
        },
        {
          heading: 'It also shows what is missing',
          paragraphs: [
            'Creating a project section is not only about deciding what to show. It also reveals which capabilities still lack sufficient public evidence.',
            'There may be genuine integration experience but no visible project that demonstrates it.',
            'There may be knowledge of Spring Boot but no published and documented application.',
            'Someone may have worked for years on enterprise systems without ever explaining the decisions that make them reliable.',
            'That gap can become a roadmap.',
            'Future projects stop being chosen only because they seem interesting. They begin to be chosen because they complete a professional picture:',
            'one can demonstrate backend and persistence; another, integration and messaging; another, security and architecture; another, responsible use of AI.',
            'A portfolio is therefore not only a record of past work. It can also organise future work.',
          ],
        },
        {
          heading: 'A professional memory',
          paragraphs: [
            'Over time, it is easy to forget how much we have done.',
            'Projects end, companies change, technologies are replaced, and details disappear behind new responsibilities.',
            'A portfolio preserves a selected memory:',
            'what I built; which problems I solved; which technologies I used; what I learned; how I thought at the time; what changed afterwards.',
            'It is not a neutral archive. Every presentation involves selection. Yet that selection makes it possible to recognise continuity where there once seemed to be isolated episodes.',
            'It also reveals evolution. An old project can represent one stage; a new one can demonstrate a change in level, methodology, or ambition.',
          ],
        },
        {
          heading: 'It is not a finished work',
          paragraphs: [
            'There is a risk of treating a portfolio as a definitive work.',
            'Trying to make everything perfect before publishing can turn it into an endless task. There will always be a missing project, translation, visual correction, or better description.',
            'But a professional identity is not finished either.',
            'A portfolio is therefore better understood as a living system. It is published when it represents the present with dignity and then evolves:',
            'projects are added; inaccuracies are corrected; experience is updated; articles are published; elements that are no longer relevant are removed; the narrative is adjusted.',
            'This evolution is not a flaw. It is part of its purpose.',
            'A portfolio should not pretend that a career is complete. It should show that it has direction.',
          ],
        },
        {
          heading: 'So, who reads it?',
          paragraphs: [
            'It may be read by a recruiter who needs to understand a profile quickly.',
            'It may be read by a technical decision-maker looking for signs of judgement and experience.',
            'It may be read by a colleague, a potential client, or someone who arrived through an article.',
            'It may also be read by almost nobody for a week.',
            'But there is another reader who is always present: the person who builds it.',
            'That reader uses the portfolio to review the past, organise the present, and project the future.',
            'Its external usefulness depends on factors we do not completely control: traffic, opportunities, selection processes, and other people’s attention.',
            'Its internal usefulness begins the moment we honestly try to answer:',
            'What do I want to show, what can I demonstrate, and what do I still need to build?',
          ],
        },
        {
          heading: 'Building to be seen and to see oneself',
          paragraphs: [
            'A portfolio must be designed for others. It needs to be clear, accessible, and easy to explore. It cannot become a purely autobiographical exercise.',
            'But it should not be measured only by the number of visits.',
            'Building it can produce something that precedes any job opportunity: a more precise understanding of one’s professional position.',
            'It forces us to find a thread between scattered experiences.',
            'It turns capabilities into evidence.',
            'It exposes contradictions.',
            'It reveals gaps.',
            'It organises future projects.',
            'Perhaps many people will not read a complete portfolio.',
            'Even so, it may be worth building.',
            'Because we are not only creating a place for others to know us.',
            'We are also building a place from which to recognise ourselves.',
          ],
        },
      ],
    },
    fr: {
      slug: 'qui-lit-un-portfolio',
      kicker: 'Identité professionnelle',
      cardCopete:
        'Avant de convaincre les autres, un portfolio oblige à ordonner son propre parcours et à décider quel professionnel on est aujourd’hui.',
      title: 'Qui lit un portfolio ?',
      copete:
        'Un portfolio semble être conçu pour les recruteurs, les clients ou les responsables techniques. Pourtant, son premier lecteur est la personne qui le crée. Avant de convaincre les autres, il oblige à ordonner son propre parcours, à choisir ce que l’on montre et à répondre à une question difficile : quel professionnel suis-je aujourd’hui ?',
      bajada:
        'Il est légitime de se demander combien de personnes visiteront un portfolio et combien de temps elles lui consacreront. Mais réduire sa valeur à l’attention extérieure revient à ignorer une dimension essentielle : le construire permet aussi de revoir sa propre histoire, de reconnaître ses capacités, de repérer ses lacunes et de décider dans quelle direction avancer.',
      sections: [
        {
          heading: 'La question inévitable',
          paragraphs: [
            'Après avoir consacré du temps à concevoir, écrire et publier un portfolio, une question difficile à éviter apparaît :',
            'Qui va lire tout cela ?',
            'La réponse la plus honnête n’est probablement pas rassurante. De nombreux recruteurs n’ouvriront le lien que quelques secondes. Certains regarderont uniquement le titre, l’expérience récente et les principales technologies. Un responsable technique visitera peut-être GitHub. D’autres ne l’ouvriront jamais.',
            'Un doute raisonnable surgit alors : vaut-il la peine de construire un portfolio si nous ignorons qui le lira ?',
            'Je crois que oui, mais pas uniquement pour les visites qu’il peut recevoir.',
            'Un portfolio n’est pas seulement un outil de communication tourné vers l’extérieur. C’est aussi un moyen de s’observer professionnellement avec une certaine distance.',
          ],
        },
        {
          heading: 'Un récit, pas seulement une liste',
          paragraphs: [
            'Un CV résume. LinkedIn classe. GitHub expose des dépôts. Un portfolio permet de construire un récit.',
            'Il ne se limite pas à énumérer des emplois, des technologies et des études. Il peut montrer comment ils s’articulent :',
            'quelle expérience je possède ; quels problèmes je sais résoudre ; comment je travaille ; ce que je construis ; ce que je pense du secteur ; vers quoi je souhaite avancer.',
            'Un parcours peut comprendre le backend, l’architecture, l’intégration, la coordination technique et le développement full-stack. Présentés sous forme de liste, ces éléments semblent fragmentés. Dans un portfolio, ils peuvent former une identité professionnelle compréhensible.',
            'Le site fonctionne comme une interface entre un parcours complexe et quelqu’un qui ne le connaît pas encore.',
          ],
        },
        {
          heading: 'Le premier lecteur, c’est soi-même',
          paragraphs: [
            'En construisant mon portfolio, j’ai compris que de nombreuses décisions apparemment visuelles concernaient en réalité mon identité professionnelle.',
            'Quel titre devais-je utiliser ? Senior Software Engineer ou Senior Software Developer ? Quelle place Java devait-il occuper ? Devais-je me présenter principalement comme développeur backend ou full-stack ? Comment intégrer l’intelligence artificielle sans la faire paraître plus importante que dix-huit années d’expérience ? Quels emplois et projets représentaient le mieux mon parcours actuel ?',
            'On ne répond pas à ces questions en modifiant du CSS. Elles exigent de revoir sa propre histoire et de décider quelle version de celle-ci on souhaite assumer publiquement.',
            'En essayant d’expliquer à quelqu’un d’autre qui je suis professionnellement, j’ai d’abord dû me l’expliquer à moi-même.',
          ],
        },
        {
          heading: 'Choisir signifie aussi renoncer',
          paragraphs: [
            'Un long parcours contient trop d’expériences, de technologies et de responsabilités pour leur accorder à toutes le même poids.',
            'Essayer d’inclure chaque élément ne produit pas une image plus complète. Cela produit généralement du bruit.',
            'Me présenter comme développeur Java senior signifie que d’autres technologies occupent une place complémentaire. Mettre en avant les applications d’entreprise et l’intégration signifie ne pas centrer le discours sur des travaux frontend isolés.',
            'Parler de développement augmenté par l’IA exige de préciser que la direction, la révision et la responsabilité restent humaines.',
            'Présenter des projets de portfolio exige de les distinguer des projets commerciaux ou réalisés pour des clients.',
            'Ces choix nous obligent à abandonner l’idée qu’une identité professionnelle doit contenir toutes les versions possibles de nous-mêmes.',
            'Un portfolio ne répond pas exhaustivement à la question de savoir qui j’ai été. Il tente de montrer qui je suis aujourd’hui et ce que l’on peut attendre de moi.',
          ],
        },
        {
          heading: 'La cohérence n’apparaît pas toute seule',
          paragraphs: [
            'Nos différents canaux professionnels racontent souvent des histoires différentes.',
            'Le CV peut nous présenter d’une manière et LinkedIn d’une autre. GitHub peut être dominé par d’anciens dépôts qui ne représentent plus notre niveau. Une biographie écrite des années auparavant peut continuer à décrire des objectifs que nous n’avons plus.',
            'Tant que ces éléments restent séparés, les contradictions peuvent passer inaperçues. Le portfolio les rassemble.',
            'Si quelqu’un se présente comme développeur backend senior alors que ses dépôts visibles ne contiennent que des exercices élémentaires, il existe une incohérence.',
            'S’il affirme utiliser l’intelligence artificielle professionnellement sans pouvoir expliquer comment il l’utilise ni quelle responsabilité il conserve, il en existe une autre.',
            'Construire un portfolio oblige à examiner ces fractures et à aligner la manière dont nous nous présentons sur ce que nous pouvons réellement soutenir.',
          ],
        },
        {
          heading: 'Des affirmations aux preuves',
          paragraphs: [
            'Un CV se compose principalement d’affirmations :',
            'Expérience en Java. Connaissance de l’intégration. Capacité à développer des applications full-stack. Utilisation professionnelle de l’intelligence artificielle.',
            'Un portfolio permet d’accompagner ces affirmations de preuves.',
            'Un projet peut montrer le problème, l’architecture, les technologies, les tests, le temps de développement, la méthodologie, ses limites et le dépôt.',
            'Un article peut montrer la manière dont on réfléchit à une question technique ou professionnelle.',
            'Le site lui-même peut devenir une preuve de conception, d’internationalisation, d’accessibilité, de SEO, de déploiement et de maintenance.',
            'Un bon portfolio ne remplace pas l’expérience, mais réduit la distance entre l’affirmation et la démonstration.',
          ],
        },
        {
          heading: 'Il montre aussi ce qui manque',
          paragraphs: [
            'Créer une section de projets ne consiste pas seulement à décider ce que l’on montre. Cela permet aussi de découvrir quelles capacités ne disposent pas encore de preuves publiques suffisantes.',
            'Il peut exister une véritable expérience de l’intégration sans aucun projet visible pour la démontrer.',
            'On peut connaître Spring Boot sans disposer d’une application publiée et documentée.',
            'On peut avoir travaillé pendant des années sur des systèmes d’entreprise sans jamais expliquer les décisions qui les rendent fiables.',
            'Cette lacune peut devenir une feuille de route.',
            'Les prochains projets ne sont plus choisis uniquement parce qu’ils semblent intéressants. Ils commencent à être choisis parce qu’ils complètent une image professionnelle :',
            'l’un peut démontrer le backend et la persistance ; un autre, l’intégration et la messagerie ; un autre, la sécurité et l’architecture ; un autre, l’utilisation responsable de l’IA.',
            'Le portfolio n’est donc pas seulement un registre du travail passé. Il peut aussi organiser le travail futur.',
          ],
        },
        {
          heading: 'Une mémoire professionnelle',
          paragraphs: [
            'Avec le temps, il est facile d’oublier tout ce que l’on a accompli.',
            'Les projets se terminent, les entreprises changent, les technologies sont remplacées et les détails disparaissent derrière de nouvelles responsabilités.',
            'Un portfolio conserve une mémoire sélectionnée :',
            'ce que j’ai construit ; les problèmes que j’ai résolus ; les technologies que j’ai utilisées ; ce que j’ai appris ; ma manière de penser à ce moment-là ; ce qui a changé ensuite.',
            'Ce n’est pas une archive neutre. Toute présentation implique une sélection. Mais cette sélection permet de reconnaître une continuité là où il semblait n’y avoir que des épisodes isolés.',
            'Elle permet également d’observer l’évolution. Un ancien projet peut représenter une étape ; un nouveau peut montrer un changement de niveau, de méthodologie ou d’ambition.',
          ],
        },
        {
          heading: 'Ce n’est pas une œuvre achevée',
          paragraphs: [
            'Il existe un risque de traiter le portfolio comme une œuvre définitive.',
            'Chercher à tout rendre parfait avant de publier peut en faire une tâche interminable. Il manquera toujours un projet, une traduction, une correction visuelle ou une meilleure description.',
            'Mais une identité professionnelle n’est pas achevée non plus.',
            'Il vaut donc mieux comprendre le portfolio comme un système vivant. Il est publié lorsqu’il représente dignement le présent, puis il évolue :',
            'des projets sont ajoutés ; des imprécisions sont corrigées ; l’expérience est actualisée ; des articles sont publiés ; les éléments devenus inutiles sont supprimés ; le discours est ajusté.',
            'Cette évolution n’est pas une défaillance. Elle fait partie de sa fonction.',
            'Le portfolio ne devrait pas prétendre qu’un parcours est achevé. Il devrait montrer qu’il a une direction.',
          ],
        },
        {
          heading: 'Alors, qui le lit ?',
          paragraphs: [
            'Il peut être lu par un recruteur qui doit comprendre rapidement un profil.',
            'Il peut être lu par un responsable technique qui cherche des signes de jugement et d’expérience.',
            'Il peut être lu par un collègue, un client potentiel ou quelqu’un arrivé depuis un article.',
            'Il peut également n’être lu par presque personne pendant une semaine.',
            'Mais un autre lecteur est toujours présent : la personne qui le construit.',
            'Ce lecteur utilise le portfolio pour revoir son passé, ordonner son présent et projeter son avenir.',
            'Son utilité extérieure dépend de facteurs que nous ne contrôlons pas complètement : le trafic, les opportunités, les processus de recrutement et l’attention des autres.',
            'Son utilité intérieure commence dès que nous essayons de répondre honnêtement :',
            'Qu’est-ce que je veux montrer, qu’est-ce que je peux démontrer et que me reste-t-il à construire ?',
          ],
        },
        {
          heading: 'Construire pour être vu et pour se voir',
          paragraphs: [
            'Un portfolio doit être pensé pour les autres. Il doit être clair, accessible et facile à parcourir. Il ne peut pas devenir un exercice purement autobiographique.',
            'Mais il ne devrait pas non plus être mesuré uniquement au nombre de visites.',
            'Sa construction peut produire quelque chose qui précède toute opportunité professionnelle : une compréhension plus précise de sa propre position.',
            'Elle oblige à trouver un fil entre des expériences dispersées.',
            'Elle transforme des capacités en preuves.',
            'Elle expose les contradictions.',
            'Elle révèle les lacunes.',
            'Elle organise les projets futurs.',
            'Peut-être que beaucoup de personnes ne liront pas un portfolio en entier.',
            'Malgré cela, il peut valoir la peine de le construire.',
            'Car nous ne créons pas seulement un lieu où les autres peuvent nous connaître.',
            'Nous construisons aussi un lieu depuis lequel nous pouvons nous reconnaître.',
          ],
        },
      ],
    },
  },
}

export default whoReadsPortfolio
